name: 软件编译

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: '是否开启SSH'   #默认 false ，true 为开启
        required: false
        default: 'false'

env:
  GITHUB_LINK: https://github.com/${{github.repository}}
  GIT_REPOSITORY: ${{github.repository}}
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04

    name: 编译${{matrix.target}}
    strategy:
      fail-fast: false
      matrix:
        target: [openwrt_21.02.5]

    steps:
    - name: 准备结束
      uses: actions/checkout@main

    - name: 部署编译环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install $(curl -fsSL git.io/depends-ubuntu-2004)
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
        
    - name: 
