#
# Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
#
# 一次只能编译一个

name: OpenWrt编译(手动指定版本)

on:
  workflow_dispatch:
    inputs:
      target:
        description: '选择版本'
        required: true
        default: 'openwrt_24.10.0'
#  repository_dispatch:

env:
  GITHUB_LINK: https://github.com/${{github.repository}}
  GIT_REPOSITORY: ${{github.repository}}
  UPLOAD_BIN_DIR: true                         #上传 bin 目录。即包含所有 ipk 文件和固件的目录。默认false
  UPLOAD_FIRMWARE: true                         #上传固件目录。默认true
  UPLOAD_RELEASE: true                         #上传固件到 releases 。默认false
  UPLOAD_TRANSFER: false                        #奶牛快传和wetransfer快传

  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-24.04

    #赋予写入权限
 #   permissions:
 #     contents: write
      
    #选择系统版本
    name: 编译${{github.event.inputs.target}}
    strategy:
      fail-fast: true                      # true：只要流程中有失败，自动停止所有流程

    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 512
        swap-size-mb: 1024
        remove-dotnet: 'true'

    - name: 拉取仓库
      uses: actions/checkout@main

    - name: 清理磁盘空间
      uses: jlumbroso/free-disk-space@main
      with:
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true       # 如果你不使用 Docker，可以设为 true
        swap-storage: true
        tool-cache: false          # 保留工具缓存，避免误删 Python3 等

    - name: 查看磁盘空间
      run: |
        echo "当前磁盘空间："
        df -h

    # - name: 清理磁盘空间
    #   run: |
    #     echo "🧹 开始清理磁盘空间..."
    #     sudo rm -rf /usr/share/dotnet
    #     sudo rm -rf /usr/local/lib/android
    #     sudo rm -rf /opt/ghc
    #     sudo rm -rf /opt/hostedtoolcache/CodeQL
    #     sudo rm -rf /opt/microsoft
    #     sudo rm -rf /opt/pipx
    #     sudo rm -rf /usr/share/swift
    #     sudo apt-get clean
    #     sudo apt-get autoremove -y
    #     echo "✅ 清理完成，当前磁盘空间："
    #     df -h

    - name: 配置git环境，使用自己的token(私有仓库时使用)
      uses: de-vri-es/setup-git-credentials@v2
      with:
        credentials: https://pencail:${{ secrets.TOKEN_PENCAIL }}@github.com/

    - name: 检测脚本设置
      run: |
        source "${GITHUB_WORKSPACE}/build/${{github.event.inputs.target}}/settings.ini"

        echo "REPO_URL=${REPO_URL}" >> ${GITHUB_ENV}
        echo "REPO_BRANCH=${REPO_BRANCH}" >> ${GITHUB_ENV}
        echo "CONFIG_FILE=${CONFIG_FILE}" >> ${GITHUB_ENV}
        echo "FEEDS_CONF=${FEEDS_CONF}" >> ${GITHUB_ENV}
        echo "DIY_P1_SH=${DIY_P1_SH}" >> ${GITHUB_ENV}
        echo "DIY_P2_SH=${DIY_P2_SH}" >> ${GITHUB_ENV}

    #     sudo -E apt-get -qq install ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev

    #     sudo -E apt-get -qq install ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache clang cmake cpio curl device-tree-compiler flex gawk gcc-multilib g++-multilib gettext genisoimage git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev libreadline-dev libssl-dev libtool llvm lrzsz msmtp ninja-build p7zip p7zip-full patch pkgconf python3 python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev

    - name: 部署编译环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache clang cmake cpio curl device-tree-compiler flex gawk gcc-multilib g++-multilib gettext genisoimage git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses-dev libpython3-dev libreadline-dev libssl-dev libtool llvm lrzsz msmtp ninja-build p7zip p7zip-full patch pkgconf python3 python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: 下载固件
      working-directory: /workdir
      run: |
        df -hT $PWD
        git clone $REPO_URL -b $REPO_BRANCH openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt

    - name: 加载自定义源(feeds)，同时运行part1脚本
      run: |
        if [ -f "build/${{github.event.inputs.target}}/$FEEDS_CONF" ]; then
          cp build/${{github.event.inputs.target}}/$FEEDS_CONF openwrt/feeds.conf.default
        fi
        
        chmod +x build/${{github.event.inputs.target}}/$DIY_P1_SH
        cd openwrt
        /bin/bash "$GITHUB_WORKSPACE/build/${{github.event.inputs.target}}/$DIY_P1_SH"
#        [ -e $FEEDS_CONF ] && 

    - name: 更新自定义源(feeds)
      run: cd openwrt && ./scripts/feeds update -a
    
    - name: 删除自定义源中的argon
      working-directory: openwrt
      run: |
        rm -rf feeds/pencail/luci-theme-argon
        rm -rf feeds/pencail/luci-app-argon-config
#        rm -rf feeds/kenzo/luci-theme-argon
#        rm -rf feeds/kenzo/luci-them-argone
#        rm -rf feeds/kenzo/luci-app-argone-config
    
    - name: 安装自定义源(feeds)
      run: cd openwrt && ./scripts/feeds install -a
      

    - name: 加载配置文件(config)，同时运行part2脚本
      run: |
        cp build/${{github.event.inputs.target}}/$CONFIG_FILE openwrt/.config
        chmod +x build/${{github.event.inputs.target}}/$DIY_P2_SH    
        cd openwrt
        /bin/bash "$GITHUB_WORKSPACE/build/${{github.event.inputs.target}}/$DIY_P2_SH"
#        [ -e $CONFIG_FILE ] && 
        
    - name: 加载file文件
      run: |
        if [ -n "$(ls -A "build/${{github.event.inputs.target}}/DIY" 2>/dev/null)" ]; then
          cp -Rf $GITHUB_WORKSPACE/build/${{github.event.inputs.target}}/DIY/* openwrt
        fi

    - name: 加载内核MD5文件
      run: |
        if [ -n "$(ls -A "build/${{github.event.inputs.target}}/md5.vermagic" 2>/dev/null)" ]; then
          cp -Rf $GITHUB_WORKSPACE/build/${{github.event.inputs.target}}/md5.vermagic openwrt/.vermagic
        fi

    - name: 下载软件包
      working-directory: openwrt
      id: package
      run: |
        make defconfig
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
    
    - name: 加载补丁文件
      working-directory: openwrt
      run: |
        if [ -n "$(ls -A "$GITHUB_WORKSPACE/build/${{github.event.inputs.target}}/patches" 2>/dev/null)" ]; then
          chmod +x $GITHUB_WORKSPACE/scripts/apply_all_patches.sh
          cp -Rf $GITHUB_WORKSPACE/build/${{github.event.inputs.target}}/patches patches
          echo "🧩 正在应用补丁文件..."  
          /bin/bash $GITHUB_WORKSPACE/scripts/apply_all_patches.sh patches $GITHUB_WORKSPACE/build/${{github.event.inputs.target}}/patchmap.yml logs/patchlog.txt

          echo "🧩 补丁日志预览："
          tail -n 10 logs/patchlog.txt || echo "(⚠️ 无日志输出)"
        fi

    - name: 上传补丁日志
      uses: actions/upload-artifact@main
      if: success()
      with:
        name: patchlog
        path: openwrt/logs/patchlog.txt

    - name: 开始编译
      id: compile
      run: |
        cd openwrt
        echo -e "$(nproc) thread compile"

        if !(make -j$(nproc) || make -j1 || make -j1 V=s); then
          echo "编译失败，终止任务" 
          exit 1
        fi
        
        echo "status=success" >> $GITHUB_OUTPUT
        grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
        [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
        echo "FILE_DATE=$(date +"%Y.%m.%d-%H.%M")" >> $GITHUB_ENV

    - name: 检查空间使用情况
      if: (!cancelled())
      run: df -hT

    - name: 上传bin文件夹(固件+ipk)在github空间
      uses: actions/upload-artifact@main
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
      with:
        name: OpenWrt_bin${{ env.DEVICE_NAME }}_${{ env.FILE_DATE }}
        path: openwrt/bin

    - name: 整理固件文件夹
      id: organize
      if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      run: |
        cd openwrt/bin/targets/*/*
        rm -rf packages
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT

    - name: 上传固件在github空间
      uses: actions/upload-artifact@main
      if: steps.organize.outputs.status == 'success' && !cancelled()
      with:
        name: OpenWrt_firmware${{ env.DEVICE_NAME }}_${{ env.FILE_DATE }}
        path: ${{ env.FIRMWARE }}

#    - name: 生成tag
#      id: tag
#      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
#      run: |
#        echo "release_tag=$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_OUTPUT
#        touch release.txt
#        [ $UPLOAD_COWTRANSFER = true ] && echo "🔗 [Cowtransfer](${{ steps.cowtransfer.outputs.url }})" >> release.txt
#        [ $UPLOAD_WETRANSFER = true ] && echo "🔗 [WeTransfer](${{ steps.wetransfer.outputs.url }})" >> release.txt
#        echo "status=success" >> $GITHUB_OUTPUT

#    - name: 自动发布固件
#      uses: softprops/action-gh-release@v1
#      if: steps.tag.outputs.status == 'success' && !cancelled()
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      with:
#        tag_name: ${{ steps.tag.outputs.release_tag }}
#        body_path: release.txt
#        files: ${{ env.FIRMWARE }}/*

    - name: 上传固件到「奶牛快传」和「wetransfer」
      id: transfer
      if: steps.organizer.outputs.status == 'success' && env.UPLOAD_TRANSFER == 'true' && !cancelled()
      run: |
        curl -fsSL git.io/file-transfer | sh
        ./transfer cow --block 2621440 -s -p 64 --no-progress ${FIRMWARE} 2>&1 | tee cowtransfer.log
        echo "::warning file=cowtransfer.com::$(cat cowtransfer.log | grep https)"
        curl -fsSL git.io/file-transfer | sh
        ./transfer wet -s -p 16 --no-progress ${FIRMWARE} 2>&1 | tee wetransfer.log
        echo "::warning file=wetransfer.com::$(cat wetransfer.log | grep https)"
        echo "status=success" >> $GITHUB_OUTPUT
        
    - name: 提取发布用的「奶牛快传」跟「WeTransfer」的链接
      if: steps.organizer.outputs.status == 'success' && steps.transfer.outputs.status == 'success' && !cancelled()
      run: |
        curl -fsSL git.io/file-transfer | sh
        ./transfer cow --block 2621440 -s -p 64 --no-progress ${FIRMWARE} 2>&1 | tee cowtransfer.log
        echo "COWTRANSFER_URL=$(cat cowtransfer.log | grep https | cut -f3 -d" ")" >> $GITHUB_ENV 
        curl -fsSL git.io/file-transfer | sh
        ./transfer wet -s -p 16 --no-progress ${FIRMWARE} 2>&1 | tee wetransfer.log
        echo "WETRANSFER_URL=$(cat wetransfer.log | grep https | cut -f3 -d" ")" >> $GITHUB_ENV

    - name: 生成tag
      id: tag
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      run: |
        echo "release_tag=$(date +"%Y.%m.%d-%H.%M")" >> $GITHUB_OUTPUT
        echo "status=success" >> $GITHUB_OUTPUT

    - name: 自动发布固件
      uses: softprops/action-gh-release@v2
      if: steps.tag.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: ${{ env.FILE_DATE }} 「 ${{ env.REPO_BRANCH }} 」固件
        tag_name: ${{ steps.tag.outputs.release_tag }}
        body: |
            ☆  源码 : ${{ env.REPO_URL }}
            ☆  分支 : ${{ env.REPO_BRANCH }}
            ☆  感谢源码作者无私分享！

#            🎉 [ ${{matrix.target}} ]固件下载 ✨
            
#            💐 奶牛快传(国内高速🚀下载)： ${{ env.COWTRANSFER_URL }}
            
#            ⛄ WeTransfer(国外高速🚀下载)： ${{ env.WETRANSFER_URL }}
            
#            🌴 链接有效期为7天，无需注册直接下载 🐤
        files: ${{ env.FIRMWARE }}/*

    - name: telegram通知(编译成功)
      uses: appleboy/telegram-action@master
      if: steps.organize.outputs.status == 'success'
      with:
        to: ${{secrets.TELEGRAM_CHAT_ID}}
        token: ${{secrets.TELEGRAM_TOKEN}}
        message: |
           「 ${{ env.REPO_BRANCH }} 」固件编译成功
           请前往查看 https://github.com/${{ github.repository }}/releases
           时间：${{ steps.tag.outputs.release_tag }}

    - name: telegram通知(编译失败)
      uses: appleboy/telegram-action@master
      if: steps.organize.outputs.status != 'success'
      with:
        to: ${{secrets.TELEGRAM_CHAT_ID}}
        token: ${{secrets.TELEGRAM_TOKEN}}
        message: |
           「 ${{ env.REPO_BRANCH }} 」固件编译失败
           请前往查看 https://github.com/${{ github.repository }}/action
           编译时间：${{ env.FILE_DATE }}

    - name: 删除工作流
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 3

    - name: 删除旧的Releases
      uses: dev-drprasad/delete-older-releases@v0.1.0
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      with:
        keep_latest: 5
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
