name: 测试2

on:
  workflow_dispatch:
    inputs:
      target:
        description: '选择版本'
        required: false
        default: 'ssh'

env:
  GITHUB_LINK: https://github.com/${{github.repository}}
  GIT_REPOSITORY: ${{github.repository}}
  UPLOAD_BIN_DIR: true                         #上传 bin 目录。即包含所有 ipk 文件和固件的目录。默认false
  UPLOAD_FIRMWARE: true                         #上传固件目录。默认true
  UPLOAD_RELEASE: true                         #上传固件到 releases 。默认false
  UPLOAD_TRANSFER: false                        #奶牛快传和wetransfer快传

  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04
    
    #赋予写入权限
    permissions:
      contents: write

    #选择系统版本
    name: 编译${{matrix.target}}
    strategy:
      fail-fast: false                      # true：只要流程中有失败，自动停止所有流程
      matrix:
        target: ${{github.event.inputs.target}}
        
    steps:
    - name: 拉取仓库
      uses: actions/checkout@main

    - name: 检测脚本设置
      run: |
        source "${GITHUB_WORKSPACE}/build/${{matrix.target}}/settings.ini"

        echo "REPO_URL=${REPO_URL}" >> ${GITHUB_ENV}
        echo "REPO_BRANCH=${REPO_BRANCH}" >> ${GITHUB_ENV}
        echo "CONFIG_FILE=${CONFIG_FILE}" >> ${GITHUB_ENV}
        echo "FEEDS_CONF=${FEEDS_CONF}" >> ${GITHUB_ENV}
        echo "DIY_P1_SH=${DIY_P1_SH}" >> ${GITHUB_ENV}
        echo "DIY_P2_SH=${DIY_P2_SH}" >> ${GITHUB_ENV}

